### ISSUE TITLE
icons desktop shading

### ISSUE THREAD

**Issue by vejobuj** [shimmerproject/Blackbird#10]
The shading of the text of the icons on the desktop have not a very good renderings.
http://i.imgur.com/MFdpfbz.png

**Comment by EricKoegel** [comment]
Does this look better to you?

**Comment by vejobuj** [comment]
Thanks you, it's nice :) http://i.imgur.com/9ZNwqsk.png

**Comment by EricKoegel** [comment]
Closing bug report, thanks for verifying the fix!
