### ISSUE TITLE
xfce4-screenshooter cannot select a place on the desktop for a window fragment

### ISSUE THREAD

**Issue by ghost** [shimmerproject/Blackbird#28]
Hello!

Thank you for an excellent theme!

I have the following problem though, which only happens when Blackbird is active:

Using xfce4-screenshooter to "select a part of a screen" is not possible, because all the screen is drawn as a solid gray colour. 

This doesn't happen on, for example, xfce-dusk.

I am using xfce 4.12.

**Comment by truethug** [comment]
What do you think about system d?
