### ISSUE TITLE
checkbox blank

### ISSUE THREAD

**Issue by vejobuj** [shimmerproject/Blackbird#5]
since few last commits, the check-box are blank

**Comment by EricKoegel** [comment]
Hey, I proposed those changes so I figure I should help try to fix them. The linked patch should fix the checkbox/radio button states so they can be in an active state again. Dunno how I managed to overlook that!
If you could verify this patch works I'll happily submit a pull request for further review. Thanks!

**Comment by truethug** [comment]
This is why open source works. Props

-TrueThug

**Comment by vejobuj** [comment]
Thanks a lot, now it works well ! :) 
Just one thing is with the grayed entry's menu are invisible.
http://i.imgur.com/zZkaDBZ.png
