### ISSUE TITLE
Grayed entry's menu are invisible.

### ISSUE THREAD

**Issue by vejobuj** [shimmerproject/Blackbird#6]
Grayed entry's menu are invisible.
http://i.imgur.com/zZkaDBZ.png

**Comment by EricKoegel** [comment]
The attached patch fixes it in the Gtk2 menus for me. Can you try out the patch to see if it's enough for you?

**Comment by vejobuj** [comment]
wow very nice :) http://i.imgur.com/jeAhQeJ.png
Thank you very much for the quick response and the fix :)
:+1:
